### ISSUE TITLE
Support for custom Markers

### ISSUE THREAD

**Issue by jorgecoca** [bmw-tech/atlas#14]
As a consumer of this map, I'd like to set my own custom marker in the map.

**Comment by felangel** [comment]
@jorgecoca we need to decide if we need this urgently or if we can wait until https://github.com/flutter/flutter/issues/25040 is resolved. I would prefer waiting because the alternative is we need to generate a `BitMap` and the whole process becomes asynchronous. Thoughts?

**Comment by jorgecoca** [comment]
Sounds good to me to wait. This should not be fixed, but instead, in lower levels. Let's keep this open though for tracking purposes.

**Comment by victorbucutea** [comment]
There is another feature request on this subject #24213.
