### ISSUE TITLE
Update google_atlas README.md with steps required for iOS

### ISSUE THREAD

**Issue by ezmeev** [bmw-tech/atlas#37]
As a consumer of `google_atlas` maps provider for iOS app, I'd like to have couple additional steps in `Setup` section of README.md. Steps I'd suggest are:
1. Short explanation of how to setup Google Maps API key of iOS app. I found this comment very helpful: https://github.com/flutter/flutter/issues/17894#issuecomment-449887697. I know that there issue open for `flutter` repo to fix that, but it's open since May 2018, and not sure if it would be fixed soon :)
2. Short note regarding requirement to have `io.flutter.embedded_views_preview` enabled as explained here: https://github.com/flutter/flutter/issues/26893#issuecomment-474725615. BUT this  issue probably will be fixed soon, so we can have a note about that as well.

ps. I can pickup this issue if you guys think that this proposal makes sense.

**Comment by felangel** [comment]
@ezmeev I agree with the proposal 👍

If you have some free time it would be great if you could pick it up 💯

**Comment by jorgecoca** [comment]
Go for it! ;)
