### ISSUE TITLE
[question] Support open map tiles

### ISSUE THREAD

**Issue by moovida** [bmw-tech/atlas#42]
I am trying to understand what it would need to support Openstreetmap tiles or in any case tiles server in a TMS specification. I gave a quick look at the google atlas plugin, but wasn't able to find it there. So I assume it is in atlas itself and supports only a predefined tiling schema. 

Would it be possible to have a short workflow about the effort and feasibility to contribute TMS tiles support?

**Comment by kleeb** [comment]
what kind of platforms do you currently support ? anything except Google Maps ?

**Comment by jorgecoca** [comment]
Hey! Sorry for the late response, this totally skipped our radar!
In the open, the only platform publicly supported is Google Maps, but internally there are other vendors supported. 
The challenge is not the Atlas plugin per se, but having the Flutter SDK for the map provider you would like to support (like OpenStreetMap, or Mapbox, for example). Once you have the SDKs, the Atlas plugin should be relatively easy.

Let us know if there's anything we could do to support adding more map providers to the combo ;)

**Comment by kleeb** [comment]
HERE maps SDK support would be a big one!
https://developer.here.com/documentation#maps_section

**Comment by jorgecoca** [comment]
I'm afraid that the HERE Maps would need to provide an SDK first, which is out of our scope...

**Comment by felangel** [comment]
> I'm afraid that the HERE Maps would need to provide an SDK first, which is out of our scope...

Or someone needs to create a plugin which wraps the native iOS and Android SDKs

**Comment by kleeb** [comment]
there is already a plugin https://github.com/etzuk/flutter_here_maps
dart code is generated with protobuf

**Comment by jorgecoca** [comment]
@tchabot22 @noahmateen you might want to take a look at that! ⬇️ 

> there is already a plugin https://github.com/etzuk/flutter_here_maps
> dart code is generated with protobuf

**Comment by kleeb** [comment]
Don't forget to run scripts/generate_protos.sh before setting everything up.
It's somehow missing in the README.

**Comment by kleeb** [comment]
This HERE SDK exists, but is really poor and lacks a lot features.

@jorgecoca @tchabot22 @noahmateen @felangel would you be interested in joining to develop this plugin further on, add more features etc ?

**Comment by kleeb** [comment]
another interesting provider that is not using OSM, but a hybrid vector SDK: Mapbox https://pub.dev/packages/mapbox_gl

**Comment by oguibueno** [comment]
Here SDK for Flutter (beta release)

https://developer.here.com/documentation/flutter-sdk-explore/4.3.2.0/dev_guide/index.html
