### ISSUE TITLE
Provider interface changes in a minor version

### ISSUE THREAD

**Issue by nfdz** [bmw-tech/atlas#68]
The interface of the `Provider` class had a breaking change in a minor release. I think that could be an issue for people that are implementing custom providers or just mocking them and they are using this library using the cap ^ to resolve the version. 
I don't know if the effects can be mitigated today. 

Provider:
https://github.com/bmw-tech/atlas/blob/master/packages/atlas/lib/src/provider.dart
This line:
`ArgumentCallback<CameraPosition> onCameraPositionChanged,`

**Comment by dakrawczyk** [comment]
Plan of attack after speaking with @nfdz: 
1. remove the CameraPosition update
2. publish 0.5.3
3. Re-add CameraPosition
4. publish 0.6.0
5. Submit request to unpublish 0.5.2

**Comment by dakrawczyk** [comment]
@nfdz 0.5.3 is now published. I will submit a PR bumping to 0.6.0 with the breaking change.
