### ISSUE TITLE
Marker == operator ignores anchor property

### ISSUE THREAD

**Issue by m0nac0** [bmw-tech/atlas#81]
The custom implementation of the == operator of the Marker class at https://github.com/bmw-tech/atlas/blob/becce03e1f3c45581dcc6c72c58a9e565074c0ab/packages/atlas/lib/src/marker.dart#L39-L48
ignores the anchor property. The getter for the `hashcode` takes it into account, though, and all other annotation classes also seem to check for equality of all members. If this isn't intentional, I'd be happy to supply a quick PR for this.

**Comment by oguibueno** [comment]
Fixed on https://github.com/bmw-tech/atlas/pull/122
